6 - Deploy in CF/webinar/message/urls.py
from django.contrib import admin
from django.urls import path, include
from message import views


app_name = "message" # Muss in Django 2.X hinzugefügt werden
urlpatterns = [

    # Url Patterns können auch mit Parameter verwendet werden
    path("group/delete/<int:group_id>", views.delete_group, name="deletegroup"),
    path("message/add/<int:group_id>", views.add_message, name="add"),
    path("message/add", views.add_message, name="addnone"),
]

6 - Deploy in CF/webinar/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField

# ***
# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html
# ***

# Informationen über den User
# Wird automatisch beim erzeugen eines Users erstellt mithilfe von Signals
# Auch das updaten erfolgt über Signals
# Innerhalb des Codes kann eine Phonenumber via request.user.profile.phone z.B. erreicht werden
# Für mehr Informationen bitte den Blogeintrag lesen!

class Profile(models.Model):
    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE
    )
    phone = PhoneNumberField(blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return "" + str(self.user.username)

6 - Deploy in CF/webinar/core/forms.py
from django import forms
from core.models import Profile

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["phone",]

6 - Deploy in CF/webinar/core/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth.models import User
from message.models import MessageGroup
from message.forms import AddMessageGroupForm
from core.forms import EditProfileForm
from django.contrib import messages

@login_required # Der Benutzer muss angemeldet sein damit er diese Seite öffnen kann
def home(request) :
    
    assert isinstance(request, HttpRequest)

    if request.method == "POST":   

        add_message_group_form = AddMessageGroupForm(request.POST)
        if "add_message_group_submit" in request.POST:
            if add_message_group_form.is_valid():
                # Neue Gruppe wird erstellt aber nicht direkt gespeichert
                new_group = add_message_group_form.save(commit=False)

                # Neuer Gruppe einen Owner geben (Current User)
                new_group.owner = request.user.profile

                # Neue Gruppe erstellen (in DB speichern)
                new_group.save()

                # Many to Many Daten Speichern (Empfänger)
                add_message_group_form.save_m2m()

                messages.success(request, "Gruppe \"" + str(new_group) + "\" wurde erstellt")

                #Auf die gleiche Seite zurückleiten
                return HttpResponseRedirect('')
            else:
                messages.warning(request, "Gruppe konnte nicht gespeichert werden")

    else:
        # Neue Form erstellen
        add_message_group_form = AddMessageGroupForm()

        
    return render(            
        request,
        "core/home.html",
        {
            "title" : "Startseite",
            "users" : User.objects.exclude(id=request.user.id).all(),
            "message_group" : MessageGroup.objects.filter(owner=request.user.profile),
            "add_message_group_form" : add_message_group_form,
        }        
    )

@login_required # Der Benutzer muss angemeldet sein damit er diese Seite öffnen kann
def settings(request) :
    
    assert isinstance(request, HttpRequest)

    if request.method == "POST":   

        edit_profile_form = EditProfileForm(request.POST)

        if "edit_profile_submit" in request.POST:
            if edit_profile_form.is_valid():
                edit_profile = edit_profile_form.save(commit=False)
                request.user.profile.phone = edit_profile.phone
                request.user.profile.save()

                messages.success(request, "Profil wurde angepasst")

                #Auf die gleiche Seite zurückleiten
                return HttpResponseRedirect('')
            else:
                messages.warning(request, "Profil konnte nicht gespeichert werden")

    else:
        # Neue Form erstellen
        edit_profile_form = EditProfileForm(instance=request.user.profile)

        
    return render(            
        request,
        "core/settings.html",
        {
            "title" : "Einstellungen",
            "edit_profile_form" : edit_profile_form,
        }        
    )

6 - Deploy in CF/webinar/core/templates/core/_Layout.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <title>{{title}} - Webinar SMS</title>
    <!--Let browser know website is optimized for mobile-->
     <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- Style-->
     {% load staticfiles %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'core/content/materialize.min.css' %}" />
    <!-- Sitestyle -->
    {% block style %}{% endblock %}
</head>
<body>
    {% if messages %}
        <ul class="messages" style="display: none;">
            {% for message in messages %}
                <li class="message {{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% include "core/_RenderNav.html" %}
    <div class="container">       
        {% block content %}{% endblock %}
    </div>
    <!-- Scripts -->
    <script src="{% static 'core/scripts/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'core/scripts/materialize.min.js' %}"></script>
    <script src="{% static 'core/scripts/message.js' %}"></script>
    <script>
        $(document).ready(function(){
            $(".button-collapse").sideNav();
            $('.tabs').tabs();
            $('select').material_select();
            $('.modal').modal();
        });
    </script>
    {% block script %}{% endblock %}
</body>
</html>

6 - Deploy in CF/webinar/core/templates/core/_RenderNav.html
{% load staticfiles %}  
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper cyan darken-3">
            <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
            <a href="{% url 'home' %}" class="brand-logo center">Easy SMS</a>
            <ul class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'message:addnone' %}">Neue Nachricht</a></li>   
                    <li><a class="dropdown-button" href="#!" data-activates="user_dropdown">{{user}}<i class="material-icons right">arrow_drop_down</i></a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Anmelden</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<ul id="user_dropdown" class="dropdown-content">
    <li><a href="{% url 'settings' %}">Einstellungen</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'logout' %}">Abmelden</a></li>
</ul>

<ul class="side-nav" id="mobile">
    <li><a href="{% url 'home' %}">Startseite</a></li>
    {% if user.is_authenticated %}
        <li><a href="{% url 'message:addnone' %}">Neue Nachricht</a></li>
        <li><a href="{% url 'settings' %}">Einstellungen</a></li>
        <li class="divider"></li>
        <li><a href="{% url 'logout' %}">Abmelden</a></li>
    {% else %}
        <li><a href="{% url 'login' %}">Anmelden</a></li>
    {% endif %}
</ul>
        

6 - Deploy in CF/webinar/core/templates/core/home.html
{% extends "core/_layout.html" %}
{% load staticfiles %}
{% block content %}
<div class="row">
    <div class="col s12">
        <div class="card">
            <div class="card-content">
                <h2 class="card-title">Gruppe Hinzufügen</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ add_message_group_form.as_p }}
                    <button class="btn" name="add_message_group_submit" type="submit">Änderungen Speichern</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col s12 l8">
        <div class="card">
            <div class="card-content">
                <h2 class="card-title">Meine Gruppen</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Owner</th>
                            <th>Anzahl Empfänger</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for group in message_group %}
                            <tr>
                                <td>{{group.name}}</td>
                                <td>{{group.owner}}</td>
                                <td>{{group.receiver.count}}</td>
                                <td>
                                    <a class="modal-trigger" href="#{{group.id}}_modal">Mehr Anzeigen</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col s12 l4">
        <div class="card">
            <div class="card-content">
                <h2 class="card-title">Alle Benutzer</h2>
            </div>
            <ul class="collection">
            {% for u in users %}
                <li class="collection-item avatar">
                    <img src="{% static 'core/images/default_user.svg' %}" alt="{{u.email}}" class="circle">
                    <span class="title">{{u.username}}</span>
                </li>
            {% endfor %}
            </ul>  
        </div>      
    </div>
</div>

{% for group in message_group %}
<div id="{{group.id}}_modal" class="modal">
    <div class="modal-content">
        <h4>Gruppe "{{group.name}}"</h4>
        <table>
            <tbody>
                <tr>
                    <th>Owner</th>
                    <td>{{group.owner}}</td>
                </tr>
                <tr>
                    <th>Empfänger</th>
                    <td>
                        <ul class="collection">
                        {% for r in group.receiver.all %}
                            <li class="collection-item">{{r}}</li>
                        {% endfor %}
                        </ul>
                    </td>
            </tbody>
        </table>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close btn-flat">Schliessen</a>
        {% if group.owner == user.profile %}
            <a class="modal-action btn-flat" href="{% url 'message:add' group_id=group.id %}">Neue Nachricht</a>
            <a class="modal-action red-text btn-flat" href="{% url 'message:deletegroup' group_id=group.id %}">Löschen</a>
        {% endif %}
    </div>
</div>
{% endfor %}


{% endblock %}

6 - Deploy in CF/webinar/core/templates/core/settings.html
{% extends "core/_layout.html" %}

{% block content %}
<div class="row">
    <div class="col s12 m8 offset-m2">
        <div class="card">
            <div class="card-content">
                <span class="card-title">Profil Bearbeiten</span>
                <form method="POST">
                    {% csrf_token %}
                    {{edit_profile_form.as_p}}
                    <button class="btn" name="edit_profile_submit" type="submit">Änderungen Speichern</button>
                </form>
            </div> 
        </div>
    </div>
</div>

{% endblock %}